name: propcheck
version: 0.6.0
author: Paul Brauner <polux@google.com>
description: A library for exhaustive and randomized testing of Dart properties
homepage: https://github.com/polux/propcheck
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  enumerators: '>=0.6.0 <0.7.0'
dev_dependencies:
  collection: '>=0.9.3 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
